include /home/jacco/.make/make.sysdep

# Makefile: Description
#
# Copyright:	(c) 2015 Jacco van Schaik (jacco@jaccovanschaik.net)
# Version:	$Id: Makefile 672 2015-03-20 22:01:57Z jacco $
#
# This software is distributed under the terms of the MIT license. See
# http://www.opensource.org/licenses/mit-license.php for details.

INSTALL_TOP=/usr/local
INSTALL_BIN=$(INSTALL_TOP)/bin

KBL = kbl.o

CFLAGS = -g

kbl: $(KBL)
	$(CC) $(CFLAGS) -o kbl $(KBL)

clean:
	rm -f *.o kbl core kbl.tgz

kbl.tgz: clean
	tar cvf - `ls | grep -v kbl.tgz` | gzip > kbl.tgz

install: kbl
	sudo install -D -o root -g root -m 6775 kbl $(INSTALL_BIN)/kbl

# Dependencies - generated by deps on Fri Mar 20 22:14:50 CET 2015

kbl.o: kbl.c
